name: azapay
description: AzaPay Seemless.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  awesome_card: ^1.1.0
  bloc: ^6.0.1
  camera: ^0.5.8+11
  charts_flutter: ^0.10.0
  connectivity: ^3.0.3
  contacts_service: ^0.4.6
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  data_connection_checker: ^0.3.4
  device_info: ^2.0.0
  device_preview: ^0.6.2-beta
  dio: ^3.0.10
  equatable: ^2.0.0
  expansion_tile_card: ^2.0.0
  file_picker: ^2.0.12
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.15
  firebase_ml_vision: ^0.11.0
  flare_flutter: ^2.0.3
  fluentui_system_icons: ^1.1.85
  flutter_bloc: ^6.0.1
  flutter_styled_toast: ^2.0.0
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  fresh: ^0.3.0
  fresh_dio: ^0.2.0
  google_fonts: ^1.1.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  http_parser: ^3.1.4
  hydrated_bloc: ^6.0.1
  image_cropper: ^1.3.1
  intl: ^0.16.1
  isolate_bloc: ^1.0.3
  json_annotation: ^3.0.1
  keyboard_avoider: ^0.1.2
  liquid_pull_to_refresh: ^3.0.0
  logger: ^1.0.0
  material_design_icons_flutter: ^4.0.5555
  money2: ^2.0.2
  path: ^1.7.0
  path_provider: ^1.6.24
  permission_handler: ^5.0.1
  pin_code_fields: ^7.0.0
  pin_input_text_field: ^4.0.0
  qr_flutter: ^4.0.0
  retrofit: ^1.3.4
  scroll_to_index: ^2.0.0
  smooth_page_indicator: ^0.2.0
  timer_count_down: ^2.0.0
  universal_platform: ^0.1.3
  workmanager: ^0.2.3
  dropdown_below: ^0.0.5
  font_awesome_flutter: ^8.11.0
  lottie: ^0.7.0+1
  passwordfield: ^0.0.82
  flutter_spinkit: ^5.0.0

  shared_preferences: ^0.5.4+5
  http: ^0.12.0
  geolocator: ^6.2.1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^0.41.2
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  flutter_native_splash: ^0.3.2
  freezed: ^0.12.7
  hive_generator: ^0.8.2
  json_serializable: ^3.4.1
  pedantic: ^1.9.0
  retrofit_generator: ^1.3.8+1

# dependency_overrides:
#   analyzer: 0.39.16
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/azalogo.png"

#   path: 1.7.0
flutter_launcher_name:
  name: "Azapay"

flutter_native_splash:
  image: "assets/images/splash-logo.png"
  color: "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/flare/
    - assets/doc/
    - assets/images/web_img/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DashBoard
      fonts:
        - asset: fonts/DashBoard.ttf
    - family: Merchant
      fonts:
        - asset: fonts/Merchant.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Thin.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
